# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Andrew Lujan
description: "Hi I'm Andrew/Drew, and I'm a Business Intelligence Analyst and Data Scientist.  My portfolio focuses on interesting projects I've recently undertaken, with a strong emphasis on business impact, actionable insights, and data storytelling. Please visit my Github & LinkedIn pages or checkout my projects below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "New Mexico"
resume_url: ## /docs/AndrewLujan_Resume_Updated.pdf
avatar_image: /img/1692677360563.jpeg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/andrew-lujan-81b95b182/" # Add your linkedln handle
github: "https://github.com/Drewsky33"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

